apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/nikhitapallavi/clickhouse-gitops.git
    targetRevision: main
    path: base/clickhouse-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
