apiVersion: v1
kind: ServiceAccount
metadata:
  name: goose-sa
  namespace: db-migrations
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: goose-role
  namespace: db-migrations
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: goose-rolebinding
  namespace: db-migrations
subjects:
- kind: ServiceAccount
  name: goose-sa
  namespace: db-migrations
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: goose-role
